### PR TITLE
updated version details for hexo, joplin, bit, Koha, espocrm

### PR DESCRIPTION
**Pull request by pramit-d**
added bit #153, Koha #154, espocrm #155 to OSSP-master.js
added 153-bit-Versiondetails.json
added 154-koha-Versiondetails.json
added 155-espocrm-Versiondetails.json

modified 151-hexo-Versiondetails.json >> cve_details : "Not Available"

updated 154-koha-Versiondetails.json > 154-Koha-Versiondetails.json
added scorecard details for hexo, joplin, bit, Koha. espocrm in versiondetails

### CODE REVIEW

**Review by asa1997 — CHANGES_REQUESTED** [review]
Please rename the version details file for Koha. koha -> Koha

**Comment by pramit-d** [comment]
> Please rename the version details file for Koha. koha -> Koha

done

**Review by asa1997 — CHANGES_REQUESTED** [review]
Please rename the koha file to match the name of the repo.

**Comment by pramit-d** [comment]
@asa1997 the repo name is Koha, I have changed everywhere as 'Koha'

**Comment by asa1997** [comment]
@pramit-d Please resolve the conflicts as well.

**Pull request closed without merging**
