### PR TITLE
version details of gramine, logstash, struts, threatplaybook

### PR DESCRIPTION
**Pull request by sand-hya**
#343 #289 #290 #292

### CODE REVIEW

**Review by sudhirverma — COMMENTED** [review]
Please tag issue in description section.

**Comment by asa1997** [comment]
@sand-hya Please address the comment.

**Review by sudhirverma — APPROVED** [review]

**Comment by sudhirverma** [comment]
@sand-hya don't close the PR after approval we need to merge the PR

**Comment by sand-hya** [comment]
The version details for issues #343 , #289 , #290 , #292 is added in the PR #358 along with OSSP master

**Pull request closed without merging**
